terminate check/all on failure

diff --git a/check/all b/check/all
--- a/check/all
+++ b/check/all
@@ -11,10 +11,13 @@
 cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 cd "$(git rev-parse --show-toplevel)"
 
+# Exit immediately if a check fails, unless run with "-f"/"--force"
+[[ "$1" =~ ^(-f|--force)$ ]] || set -e
+
 # tests are ordered based on importance (e.g. when format fails, it often means
 # there is a syntax error) and speed (slow checks last)
 echo "Running format check"
-check/format || exit 1  # this syntax causes whole script to terminate if format fails
+check/format
 echo "Running flake8 check"
 check/flake8
 echo "Running type check"
