reorder format/flake8

diff --git a/check/all b/check/all
--- a/check/all
+++ b/check/all
@@ -11,12 +11,12 @@
 cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 cd "$(git rev-parse --show-toplevel)"
 
-# tests are ordered based on importance (e.g. when flake8 fails, it often means
+# tests are ordered based on importance (e.g. when format fails, it often means
 # there is a syntax error) and speed (slow checks last)
+echo "Running format check"
+check/format || exit 1  # this syntax causes whole script to terminate if format fails
 echo "Running flake8 check"
 check/flake8
-echo "Running format check"
-check/format
 echo "Running type check"
 check/mypy
 echo "Running lint check"
